#!/usr/bin/env bash
#we ara perfomor couunt number 0 to 100
x=1
while [ $x -le 100 ]
do
    if  (( x%15==0 ));then
      echo "FizzBuzz"
      
   elif  (( x%3==0 ));then
      echo "Fizz"
     
      
   elif (( x%5==0 ));then
      echo "Buzz"
         
    else
       echo $x
    fi
     x=$(( x + 1 ))
done
