#!/usr/bin/env bash
#we are use while and if
x=1
while [ $x -lt 11 ]
do
    if [ $x = 4 ];then 
      echo "bad luck"
    elif [ $x = 8 ];then
      echo "good luck"
    else
      echo "Best School"
    fi
     x=$(( x + 1 ))
done
