#!/usr/bin/env bash
#we are perform conditional while
x=1
while [ $x -lt 21 ]
do
    case $x in

        4)
	    echo $x
	    echo "bad luck from China"
	    ;;

        9)
	    echo $x
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo $x
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $x
	    ;;
    esac

     x=$(( x + 1 ))
done 
