#!/usr/bin/env bash
#bash scripts gives you information about the School
filename='school'
if [ -e "$filename" ];then
    echo "school file exists"
    if [ ! -s "$filename" ];then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$filename" ];then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
